---
- hosts: erl-t75
  roles:
    - role: install
    - role: network
    - role: unbound
      interfaces:
        - "127.0.0.1"
        - "::1"
        - "{{ vether0_ip }}"
    - role: dhcpd
    - role: router
    - role: pf
  vars:
    hostname: "erl-t75"
    domain: "my.domain"
    cnmac0_override_mac: "***REMOVED***"
    cnmac0_original_mac: "***REMOVED***"
    vether0_octet_1: "192"
    vether0_octet_2: "168"
    vether0_octet_3: "10"
    vether0_ip: "192.168.10.1"
    vether0_netmask: "255.255.255.0"
    vether0_broadcast: "192.168.10.255"
    dns_forwarders:
      - ipaddr: "195.138.80.86"
        org: "TeNeT"
      - ipaddr: "8.8.4.4"
        org: "Google"
      - ipaddr: "8.8.8.8"
        org: "Google"
    dns_records:
      - hostname: "***REMOVED***"
        ipv4addr: "192.168.10.3"
        macaddr: "***REMOVED***"
      - hostname: "***REMOVED***"
        ipv4addr: "192.168.10.10"
        macaddr: "***REMOVED***"
      - hostname: "***REMOVED***"
        ipv4addr: "192.168.10.11"
        macaddr: "***REMOVED***"
      - hostname: "***REMOVED***"
        ipv4addr: "192.168.10.12"
        macaddr: "***REMOVED***"
      - hostname: "***REMOVED***"
        ipv4addr: "192.168.10.19"
        macaddr: "***REMOVED***"
