---
- name: copy resolv.conf.tail
  template:
    src: resolv.conf.tail.j2
    dest: /etc/resolv.conf.tail
  become: yes

- name: touch file /etc/sysctl.conf
  file:
    dest: /etc/sysctl.conf
    owner: root
    group: wheel
    state: touch
  become: yes

- name: insert net.inet.ip.forwarding=1 in /etc/sysctl.conf
  lineinfile:
    state: present
    path: /etc/sysctl.conf
    regexp: '^net.inet.ip.forwarding=1'
    line: 'net.inet.ip.forwarding=1'
  become: yes

- name: load newly added sysctl values
  shell: xargs sysctl < /etc/sysctl.conf
  become: yes

- name: insert ntpd_flags="-s" in /etc/rc.conf.local
  lineinfile:
    state: present
    path: /etc/rc.conf.local
    regexp: '^ntpd_flags='
    line: 'ntpd_flags="-s"'
  become: yes

- name: copy doas conf
  template:
    src: doas.conf.j2
    dest: /etc/doas.conf
    owner: root
    group: wheel
    mode: "0644"
  become: yes
